name: reviewdog

on: [pull_request]

jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning

  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
